/**
 * Machine Monitoring API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerformanceLogEntry } from './performanceLogEntry';
import { MaintenanceRecord } from './maintenanceRecord';
import { ProductionInfo } from './productionInfo';
import { SensorData } from './sensorData';
import { ShiftInfo } from './shiftInfo';
import { ErrorLog } from './errorLog';
import { MachineDetails } from './machineDetails';
import { MachineState } from './machineState';


export interface Machine { 
    id?: string;
    name?: string | null;
    status?: MachineState;
    performance?: number;
    performanceLog?: Array<PerformanceLogEntry> | null;
    errors?: Array<string> | null;
    errorHistory?: Array<ErrorLog> | null;
    producedParts?: number;
    production?: ProductionInfo;
    details?: MachineDetails;
    maintenanceHistory?: Array<MaintenanceRecord> | null;
    liveSensors?: SensorData;
    currentShift?: ShiftInfo;
}
export namespace Machine {
}


