/**
 * Machine Monitoring API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MachineState = 0 | 1 | 2 | 3 | 4;

export const MachineState = {

    NUMBER_0: 0 as MachineState,

    NUMBER_1: 1 as MachineState,

    NUMBER_2: 2 as MachineState,

    NUMBER_3: 3 as MachineState,

    NUMBER_4: 4 as MachineState
};

