/**
 * Machine Monitoring API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MachineDetails { 
    manufacturer?: string | null;
    modelNumber?: string | null;
    lastMaintenance?: string;
    location?: string | null;
}

