/**
 * Machine Monitoring API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductionInfo { 
    currentProduct?: string | null;
    partsInBatch?: number;
    partsCompleted?: number;
    batchStartTime?: string;
}

