/**
 * Machine Monitoring API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SensorData { 
    temperatureC?: number;
    vibrationLevel?: number;
    powerConsumptionKw?: number;
}

